"""create initial schema

Revision ID: 1a9d876c1121
Revises:
Create Date: 2026-08-31 20:09:03.209564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a9d876c1121"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NORMAL",
                "DISABLED",
                name="admin_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("price_cents_per_kwh", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                name="station_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "latitude >= -90 AND latitude <= 90", name="ck_station_latitude"
        ),
        sa.CheckConstraint(
            "longitude >= -180 AND longitude <= 180", name="ck_station_longitude"
        ),
        sa.CheckConstraint("price_cents_per_kwh > 0", name="ck_station_price_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_stations_location", "stations", ["latitude", "longitude"], unique=False
    )
    op.create_index("idx_stations_status", "stations", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone", sa.String(length=11), nullable=False),
        sa.Column("nickname", sa.String(length=32), nullable=False),
        sa.Column("avatar_url", sa.String(length=255), nullable=True),
        sa.Column("balance_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NORMAL",
                "FROZEN",
                name="user_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("balance_cents >= 0", name="ck_users_balance_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_index("idx_users_status", "users", ["status"], unique=False)
    op.create_table(
        "charging_piles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pile_no", sa.String(length=32), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column(
            "pile_type",
            sa.Enum(
                "FAST",
                "SLOW",
                name="pile_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rated_power_w", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IDLE",
                "RESERVED",
                "CHARGING",
                "FAULT",
                "OFFLINE",
                name="pile_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("last_heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("rated_power_w > 0", name="ck_piles_power_positive"),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pile_no"),
    )
    op.create_index(
        "idx_piles_station_status",
        "charging_piles",
        ["station_id", "status"],
        unique=False,
    )
    op.create_table(
        "load_predictions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=True),
        sa.Column(
            "prediction_type",
            sa.Enum(
                "LOAD_W",
                "AVAILABLE_PILES",
                "CONGESTION_SCORE",
                name="prediction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("horizon_hours", sa.Integer(), nullable=False),
        sa.Column("predicted_for", sa.DateTime(), nullable=False),
        sa.Column("predicted_value", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("horizon_hours IN (1, 6, 24)", name="ck_prediction_horizon"),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "station_id",
            "prediction_type",
            "horizon_hours",
            "predicted_for",
            "model_version",
            name="uq_load_predictions_key",
        ),
    )
    op.create_index(
        "idx_predictions_lookup",
        "load_predictions",
        ["station_id", "horizon_hours", "predicted_for"],
        unique=False,
    )
    op.create_table(
        "operation_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_operation_logs_admin_created",
        "operation_logs",
        ["admin_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_operation_logs_target",
        "operation_logs",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "recharge_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recharge_no", sa.String(length=32), nullable=False),
        sa.Column("client_request_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("balance_before_cents", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_cents", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("amount_cents > 0", name="ck_recharge_amount_positive"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_request_id"),
        sa.UniqueConstraint("recharge_no"),
    )
    op.create_index(
        "idx_recharge_user_created",
        "recharge_records",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "charging_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("pile_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RESERVED",
                "CHARGING",
                "UNPAID",
                "COMPLETED",
                "CANCELLED",
                name="order_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("unit_price_cents_per_kwh", sa.Integer(), nullable=False),
        sa.Column("energy_wh", sa.BigInteger(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("reserved_at", sa.DateTime(), nullable=True),
        sa.Column("reservation_expires_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("stopped_at", sa.DateTime(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("amount_cents >= 0", name="ck_orders_amount_nonnegative"),
        sa.CheckConstraint(
            "duration_seconds >= 0", name="ck_orders_duration_nonnegative"
        ),
        sa.CheckConstraint("energy_wh >= 0", name="ck_orders_energy_nonnegative"),
        sa.ForeignKeyConstraint(
            ["pile_id"], ["charging_piles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_no"),
    )
    op.create_index(
        "idx_orders_pile_started",
        "charging_orders",
        ["pile_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "idx_orders_station_settled",
        "charging_orders",
        ["station_id", "settled_at"],
        unique=False,
    )
    op.create_index(
        "idx_orders_status_created",
        "charging_orders",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_orders_user_created",
        "charging_orders",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_orders_one_active_per_pile",
        "charging_orders",
        ["pile_id"],
        unique=True,
        sqlite_where=sa.text("status IN ('RESERVED','CHARGING')"),
    )
    op.create_index(
        "uq_orders_one_active_per_user",
        "charging_orders",
        ["user_id"],
        unique=True,
        sqlite_where=sa.text("status IN ('PENDING','RESERVED','CHARGING','UNPAID')"),
    )
    op.create_table(
        "pile_status_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pile_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column(
            "old_status",
            sa.Enum(
                "IDLE",
                "RESERVED",
                "CHARGING",
                "FAULT",
                "OFFLINE",
                name="pile_log_old_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "IDLE",
                "RESERVED",
                "CHARGING",
                "FAULT",
                "OFFLINE",
                name="pile_log_new_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "ADMIN",
                "SIMULATOR",
                "SYSTEM",
                name="pile_log_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["charging_orders.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["pile_id"], ["charging_piles.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pile_logs_pile_created",
        "pile_status_logs",
        ["pile_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_pile_logs_pile_created", table_name="pile_status_logs")
    op.drop_table("pile_status_logs")
    op.drop_index(
        "uq_orders_one_active_per_user",
        table_name="charging_orders",
        sqlite_where=sa.text("status IN ('PENDING','RESERVED','CHARGING','UNPAID')"),
    )
    op.drop_index(
        "uq_orders_one_active_per_pile",
        table_name="charging_orders",
        sqlite_where=sa.text("status IN ('RESERVED','CHARGING')"),
    )
    op.drop_index("idx_orders_user_created", table_name="charging_orders")
    op.drop_index("idx_orders_status_created", table_name="charging_orders")
    op.drop_index("idx_orders_station_settled", table_name="charging_orders")
    op.drop_index("idx_orders_pile_started", table_name="charging_orders")
    op.drop_table("charging_orders")
    op.drop_index("idx_recharge_user_created", table_name="recharge_records")
    op.drop_table("recharge_records")
    op.drop_index("idx_operation_logs_target", table_name="operation_logs")
    op.drop_index("idx_operation_logs_admin_created", table_name="operation_logs")
    op.drop_table("operation_logs")
    op.drop_index("idx_predictions_lookup", table_name="load_predictions")
    op.drop_table("load_predictions")
    op.drop_index("idx_piles_station_status", table_name="charging_piles")
    op.drop_table("charging_piles")
    op.drop_index("idx_users_status", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_stations_status", table_name="stations")
    op.drop_index("idx_stations_location", table_name="stations")
    op.drop_table("stations")
    op.drop_table("admins")
    # ### end Alembic commands ###
