"""add public station catalog fields

Revision ID: d7bda1991e30
Revises: 1a9d876c1121
Create Date: 2026-08-31 23:57:42.521075

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7bda1991e30"
down_revision: str | Sequence[str] | None = "1a9d876c1121"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("operator_name", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("service_type", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(sa.Column("district", sa.String(length=32), nullable=True))
        batch_op.add_column(
            sa.Column("region_scope", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sa.Column("location_type", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "fast_connector_count",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "slow_connector_count",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("data_source", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("external_id", sa.String(length=64), nullable=True)
        )
        batch_op.alter_column(
            "latitude", existing_type=sa.NUMERIC(precision=10, scale=7), nullable=True
        )
        batch_op.alter_column(
            "longitude", existing_type=sa.NUMERIC(precision=10, scale=7), nullable=True
        )
        batch_op.alter_column(
            "price_cents_per_kwh", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.create_index("idx_stations_district", ["district"], unique=False)
        batch_op.create_index("idx_stations_operator", ["operator_name"], unique=False)
        batch_op.create_index("idx_stations_source", ["data_source"], unique=False)
        batch_op.create_unique_constraint(
            "uq_stations_source_external_id", ["data_source", "external_id"]
        )
        batch_op.create_check_constraint(
            "ck_station_fast_connectors_nonnegative", "fast_connector_count >= 0"
        )
        batch_op.create_check_constraint(
            "ck_station_slow_connectors_nonnegative", "slow_connector_count >= 0"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    connection = op.get_bind()
    source = "BEIJING_PUBLIC_DATA_OPEN_PLATFORM"
    missing_required_fields = """
        latitude IS NULL
        OR longitude IS NULL
        OR price_cents_per_kwh IS NULL
    """
    dependent_records = """
        EXISTS (
            SELECT 1 FROM charging_piles
            WHERE charging_piles.station_id = stations.id
        )
        OR EXISTS (
            SELECT 1 FROM charging_orders
            WHERE charging_orders.station_id = stations.id
        )
        OR EXISTS (
            SELECT 1 FROM load_predictions
            WHERE load_predictions.station_id = stations.id
        )
    """
    blockers = connection.execute(
        sa.text(
            f"""
            SELECT COUNT(*) FROM stations
            WHERE ({missing_required_fields})
              AND (
                  COALESCE(data_source, '') != :source
                  OR ({dependent_records})
              )
            """
        ),
        {"source": source},
    ).scalar_one()
    if blockers:
        raise RuntimeError(
            "Cannot downgrade while stations with missing coordinates or price "
            "have dependent records; enrich or remove those dependencies first."
        )

    # Only unlinked catalog rows that cannot satisfy the previous NOT NULL
    # schema are removed. Enriched catalog rows are preserved as core stations.
    op.execute(
        sa.text(
            f"""
            DELETE FROM stations
            WHERE data_source = :source
              AND ({missing_required_fields})
              AND NOT ({dependent_records})
            """
        ).bindparams(source=source)
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stations", schema=None) as batch_op:
        batch_op.drop_constraint(
            "ck_station_slow_connectors_nonnegative", type_="check"
        )
        batch_op.drop_constraint(
            "ck_station_fast_connectors_nonnegative", type_="check"
        )
        batch_op.drop_constraint("uq_stations_source_external_id", type_="unique")
        batch_op.drop_index("idx_stations_source")
        batch_op.drop_index("idx_stations_operator")
        batch_op.drop_index("idx_stations_district")
        batch_op.alter_column(
            "price_cents_per_kwh", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "longitude", existing_type=sa.NUMERIC(precision=10, scale=7), nullable=False
        )
        batch_op.alter_column(
            "latitude", existing_type=sa.NUMERIC(precision=10, scale=7), nullable=False
        )
        batch_op.drop_column("external_id")
        batch_op.drop_column("data_source")
        batch_op.drop_column("slow_connector_count")
        batch_op.drop_column("fast_connector_count")
        batch_op.drop_column("location_type")
        batch_op.drop_column("region_scope")
        batch_op.drop_column("district")
        batch_op.drop_column("service_type")
        batch_op.drop_column("operator_name")

    # ### end Alembic commands ###
